version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: goweb
    deploy:
      replace: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3090:9065"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "3091:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redistest:
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - ./data:/data
      deploy:
        placement:
          constraints: [node.role == manager]
      networks:
        - webnet
networks:
  webnet: