package serverconfig

import "fmt"

type AutoGenerated struct {
	Logging struct {
		IncludeScopes bool `json:"IncludeScopes"`
		LogLevel      struct {
			Default string `json:"Default"`
		} `json:"LogLevel"`
	} `json:"Logging"`
	MetatraderServerInfo struct {
		Server  string `json:"Server"`
		Port    int    `json:"Port"`
		Login   int    `json:"Login"`
		Pwd     string `json:"Pwd"`
		Timeout int    `json:"Timeout"`
	} `json:"MetatraderServerInfo"`
	CrmConfig struct {
		UseRadisSession bool   `json:"UseRadisSession"`
		Debug           bool   `json:"Debug"`
		Env             string `json:"Env"`
	} `json:"CrmConfig"`
	RedisConfig struct {
		Host string `json:"Host"`
	} `json:"RedisConfig"`
}

func TestFun()  {
	fmt.Println("test")
}