// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld/helloworld.proto

It has these top-level messages:
	TestMsg
	HelloRequest
	HelloReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMsg struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *TestMsg) Reset()                    { *m = TestMsg{} }
func (m *TestMsg) String() string            { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()               {}
func (*TestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "helloworld.TestMsg")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}

// Client API for MyTest service

type MyTestClient interface {
	Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error)
}

type myTestClient struct {
	cc *grpc.ClientConn
}

func NewMyTestClient(cc *grpc.ClientConn) MyTestClient {
	return &myTestClient{cc}
}

func (c *myTestClient) Test(ctx context.Context, in *TestMsg, opts ...grpc.CallOption) (*TestMsg, error) {
	out := new(TestMsg)
	err := grpc.Invoke(ctx, "/helloworld.MyTest/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyTest service

type MyTestServer interface {
	Test(context.Context, *TestMsg) (*TestMsg, error)
}

func RegisterMyTestServer(s *grpc.Server, srv MyTestServer) {
	s.RegisterService(&_MyTest_serviceDesc, srv)
}

func _MyTest_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyTestServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.MyTest/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyTestServer).Test(ctx, req.(*TestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.MyTest",
	HandlerType: (*MyTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _MyTest_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}

func init() { proto.RegisterFile("helloworld/helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x46, 0x6f, 0xf1, 0xb8, 0xd5, 0x41, 0x50, 0x46, 0x90, 0xe5, 0xb6, 0x91, 0x14, 0x62, 0x15,
	0x65, 0x6d, 0xc5, 0xe2, 0x1a, 0xb5, 0x38, 0x38, 0x56, 0xc1, 0x3a, 0xea, 0x10, 0x85, 0xc4, 0xc4,
	0x24, 0xa2, 0xf9, 0xf7, 0x47, 0xc2, 0x2e, 0x9b, 0x62, 0xab, 0xbc, 0x4c, 0x5e, 0x98, 0x99, 0x0f,
	0xda, 0x4f, 0x52, 0xca, 0xfc, 0x19, 0xa7, 0x3e, 0xae, 0x27, 0xe4, 0xd6, 0x99, 0x60, 0x10, 0xa6,
	0x0a, 0x6b, 0xa1, 0x7e, 0x21, 0x1f, 0xb6, 0x5e, 0xe2, 0x29, 0x1c, 0x68, 0x2f, 0x9b, 0xea, 0xa2,
	0xba, 0x3a, 0xea, 0x13, 0x32, 0x06, 0xc7, 0x8f, 0x49, 0xed, 0xe9, 0xe7, 0x97, 0x7c, 0x40, 0x84,
	0xe5, 0xb7, 0xd0, 0x34, 0x28, 0x99, 0xd9, 0x25, 0xc0, 0xe0, 0x58, 0x15, 0xb1, 0x81, 0x5a, 0x93,
	0xf7, 0x42, 0x8e, 0xd2, 0x78, 0xed, 0x9e, 0xa0, 0x7e, 0x70, 0x44, 0x81, 0x1c, 0xde, 0xc3, 0xe1,
	0xb3, 0x88, 0xf9, 0x17, 0x36, 0xbc, 0x18, 0xaf, 0x6c, 0xb6, 0x3e, 0x9f, 0x79, 0xb1, 0x2a, 0xb2,
	0x45, 0x77, 0x07, 0xab, 0x6d, 0x4c, 0x53, 0x63, 0x07, 0xcb, 0x7c, 0x9e, 0x95, 0xee, 0xb0, 0xcf,
	0x7a, 0xae, 0xc8, 0x16, 0x9b, 0x1b, 0x68, 0xbf, 0x0c, 0x97, 0xce, 0xbe, 0x73, 0xfa, 0x17, 0xda,
	0x2a, 0xf2, 0x85, 0xb8, 0x39, 0xc9, 0xad, 0x5e, 0x13, 0xef, 0x52, 0x5a, 0xbb, 0xea, 0x6d, 0x95,
	0x63, 0xbb, 0xdd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xc9, 0x72, 0xe1, 0x55, 0x01, 0x00, 0x00,
}
