package main

import (
	"encoding/json"
	"fmt"
)

var str1 = `
{
"name": "lipen",
"age": 20
}
`
type AutoGenerated struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type AutoGenerated2 struct {
	Name string `json:"name1"`
	Age  int    `json:"age2"`
}

func main() {
	var a1 *AutoGenerated = nil
	err := json.Unmarshal([]byte(str1), &a1)
	if a1 == nil {
		fmt.Println("is nil")
	}
	fmt.Println(err, a1)
}