// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Helloworld {
  public static partial class MyTest2
  {
    static readonly string __ServiceName = "helloworld.MyTest2";

    static readonly grpc::Marshaller<global::Helloworld.TestMsg> __Marshaller_TestMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Helloworld.TestMsg.Parser.ParseFrom);

    static readonly grpc::Method<global::Helloworld.TestMsg, global::Helloworld.TestMsg> __Method_Test2 = new grpc::Method<global::Helloworld.TestMsg, global::Helloworld.TestMsg>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Test2",
        __Marshaller_TestMsg,
        __Marshaller_TestMsg);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Helloworld.TestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MyTest2</summary>
    public abstract partial class MyTest2Base
    {
      public virtual global::System.Threading.Tasks.Task<global::Helloworld.TestMsg> Test2(global::Helloworld.TestMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MyTest2</summary>
    public partial class MyTest2Client : grpc::ClientBase<MyTest2Client>
    {
      /// <summary>Creates a new client for MyTest2</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MyTest2Client(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MyTest2 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MyTest2Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MyTest2Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MyTest2Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Helloworld.TestMsg Test2(global::Helloworld.TestMsg request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Test2(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Helloworld.TestMsg Test2(global::Helloworld.TestMsg request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Test2, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.TestMsg> Test2Async(global::Helloworld.TestMsg request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Test2Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Helloworld.TestMsg> Test2Async(global::Helloworld.TestMsg request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Test2, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MyTest2Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new MyTest2Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MyTest2Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Test2, serviceImpl.Test2).Build();
    }

  }
}
#endregion
