package main

import (
	"fmt"
	sconfig "./serverconfig"

)

var data sconfig.AutoGenerated

func main() {
	fmt.Println("publish crm..")
	configData, err := sconfig.ReadCrmConfig("./config.json")
	if err != nil {
		fmt.Printf("read config error : %v", err)
		return
	}
	configData.JsonFilePath += "abc"
	configData.Name  += "name"
	configData.SaveToFile("./config.json")


}
