package main

import (
	sconfig "./serverconfig"
	"fmt"

	"github.com/urfave/cli"
	"os"
)

var data sconfig.AutoGenerated

const (
	dev = "dev"
	pro = "pro"
)

func main() {
	cli.NewApp().Run(os.Args)
	args := os.Args[1:]
	if len(args) <= 0 || (args[0] != dev || args[0] != pro) {
		fmt.Printf("input command dev|pro and options")
		return
	}
	fmt.Println("publish crm..")
	configData, err := sconfig.ReadCrmConfig("./config.json")
	if err != nil {
		fmt.Printf("read config error : %v", err)
		return
	}
	appSetting, err := sconfig.ReadAppSetting(configData.JsonFilePath)
	if err != nil {
		fmt.Printf("read app setting error : %v", err)
		return
	}

	devStr := args[0]
	if devStr == dev {
		appSetting.RedisConfig.Host = configData.DebugRedis
	} else if devStr == pro {
		appSetting.RedisConfig.Host = configData.ProRedisHost
	}

}
